"""Update DB

Revision ID: 3069ba39ebc3
Revises: 9746e5193e94
Create Date: 2026-05-21 09:37:56.680393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3069ba39ebc3'
down_revision: Union[str, Sequence[str], None] = '9746e5193e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_reply_to_id'), 'messages', ['reply_to_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_reply_to_id'), table_name='messages')
    op.drop_column('messages', 'reply_to_id')
    # ### end Alembic commands ###
