"""Initial Migrate

Revision ID: 44493a6f8c70
Revises: 5051c925700f
Create Date: 2026-05-20 09:47:10.656877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44493a6f8c70'
down_revision: Union[str, Sequence[str], None] = '5051c925700f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liked_tracks', sa.Column('track_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_liked_tracks_spotify_id'), table_name='liked_tracks')
    op.drop_constraint(op.f('uq_user_track_like'), 'liked_tracks', type_='unique')
    op.create_unique_constraint('uq_user_track_like', 'liked_tracks', ['user_id', 'track_id'])
    op.create_index(op.f('ix_liked_tracks_track_id'), 'liked_tracks', ['track_id'], unique=False)
    op.drop_column('liked_tracks', 'spotify_id')
    op.add_column('users', sa.Column('auth_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_users_spotify_id'), table_name='users')
    op.create_index(op.f('ix_users_auth_id'), 'users', ['auth_id'], unique=True)
    op.drop_column('users', 'spotify_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spotify_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_auth_id'), table_name='users')
    op.create_index(op.f('ix_users_spotify_id'), 'users', ['spotify_id'], unique=True)
    op.drop_column('users', 'auth_id')
    op.add_column('liked_tracks', sa.Column('spotify_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_liked_tracks_track_id'), table_name='liked_tracks')
    op.drop_constraint('uq_user_track_like', 'liked_tracks', type_='unique')
    op.create_unique_constraint(op.f('uq_user_track_like'), 'liked_tracks', ['user_id', 'spotify_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_liked_tracks_spotify_id'), 'liked_tracks', ['spotify_id'], unique=False)
    op.drop_column('liked_tracks', 'track_id')
    # ### end Alembic commands ###
