name: web-music-stream-piped

services:
  piped-backend:
    image: 1337kavin/piped:latest
    container_name: piped-backend
    restart: unless-stopped
    depends_on:
      piped-db:
        condition: service_healthy
    volumes:
      - ./piped.config.properties:/app/config.properties:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.piped-backend.rule=Host(`${PIPED_API_DOMAIN}`)
      - traefik.http.routers.piped-backend.entrypoints=websecure
      - traefik.http.routers.piped-backend.tls.certresolver=le
      - traefik.http.services.piped-backend.loadbalancer.server.port=8080
    networks:
      - traefik-proxy

  piped-proxy:
    image: 1337kavin/piped-proxy:latest
    container_name: piped-proxy
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.piped-proxy.rule=Host(`${PIPED_PROXY_DOMAIN}`)
      - traefik.http.routers.piped-proxy.entrypoints=websecure
      - traefik.http.routers.piped-proxy.tls.certresolver=le
      - traefik.http.services.piped-proxy.loadbalancer.server.port=8080
    networks:
      - traefik-proxy

  piped-db:
    image: postgres:15-alpine
    container_name: piped-db
    environment:
      POSTGRES_DB: piped
      POSTGRES_USER: piped-riku
      POSTGRES_PASSWORD: ${PIPED_DB_PASSWORD}
    volumes:
      - piped_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U piped-riku -d piped"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
    name: asseqr-system_app-network

volumes:
  piped_pgdata:
