PORT: 8080
HTTP_WORKERS: 2

# Replace these with your actual subdomains
PROXY_PART: https://piped-proxy.linkerx.dev
API_URL: https://piped-api.linkerx.dev

# Set to false to disable the public web UI (we only need the API)
DISABLE_REGISTRATION: true

hibernate.connection.url: jdbc:postgresql://piped-db:5432/piped
hibernate.connection.driver_class: org.postgresql.Driver
hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.username: piped-riku
hibernate.connection.password: rikurikuriku