PORT: 8080
HTTP_WORKERS: 2

PROXY_PART: https://piped-proxy.linkerx.dev
API_URL: https://piped-api.linkerx.dev

DISABLE_REGISTRATION: true

# YouTube cookies to bypass bot detection on this IP
COOKIE_PATH: /app/cookies.txt

hibernate.connection.url: jdbc:postgresql://piped-db:5432/piped
hibernate.connection.driver_class: org.postgresql.Driver
hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.username: piped-riku
hibernate.connection.password: rikurikuriku